<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $title; ?></title>
</head>
<body>
<?php echo $message;?>
    <form action="<?php echo $this->appUrl('index.php/add');?>" method="post" >
    <p><label>Name: </label><input type="text" name="fname" value="" /></p>
    <p><label>Surname: </label><input type="text" name="lname" value="" /></p>
    <p><label>email: </label><input type="text" name="email_id" value="" /></p>
    <p><label>Phone: </label><input type="text" name="phone" value="" /></p>
    <p><label>Department: </label><input type="text" name="department" value="" /></p>
    <p><label>password: </label><input type="text" name="password" value="" /></p>
    <p><input type="submit" name="submit" value="Submit"/></p>
</form>
</body>
</html>