<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $title; ?></title>
</head>
<body>
<?php echo $message;

$data = json_decode($list['body'])->data;
?>
    <form action="<?php echo $this->appUrl('index.php/edit/'.$data->id);?>" method="post" >
    <p><label>ID: </label><input type="text" name="id" value="<?php echo $data->id; ?>" readonly="readonly" /></p>
    <p><label>Name: </label><input type="text" name="name" value="<?php echo $data->fname; ?>" /></p>
    <p><label>Surname: </label><input type="text" name="surname" value="<?php echo $data->lname; ?>" /></p>
    <p><label>email: </label><input type="text" name="email" value="<?php echo $data->email_id; ?>" /></p>
    <p><input type="submit" name="submit" value="Submit"/></p>
</form>
</body>
</html>